FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

ENV CONFLUENCE_USERNAME=""
ENV CONFLUENCE_PASSWORD=""
ENV CONFLUENCE_URL="https://yourdomain.atlassian.net/wiki/rest/api/"
ENV CONFLUENCE_SPACE_ID="yourspace"
ENV CONFLUENCE_PARENT_PAGE_ID="12345"
ENV CONFLUENCE_PAGE_TITLE_SUFFIX="(autogenerated)"
ENV CONFLUENCE_PAGE_LABEL="markdown2confluence"
ENV MARKDOWN_FOLDER="./"
ENV MARKDOWN_SOURCE_REF=""

COPY ./markdown2confluence /app

CMD ["python", "/app/main.py"]
