
name: markdown2ConfluenceUsingAction
# on:
#   push:
#     branches:
#     paths:

jobs:
  markdown2Confluence:
    name: action-${{ github.event.repository.updated_at}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run action
        uses: innofactororg/markdown2confluence@action/1.0.10
        with:
          CONFLUENCE_USERNAME: ${{ vars.CONFLUENCE_USERNAME }}
          CONFLUENCE_PASSWORD: ${{ secrets.CONFLUENCE_PASSWORD }}
          CONFLUENCE_URL: 'https://sshjelle.atlassian.net/wiki/rest/api/'
          CONFLUENCE_SPACE_ID: 'TSTmarkdow'
          CONFLUENCE_PARENT_PAGE_ID: '65777'
          MARKDOWN_FOLDER: './markdown2confluence'
          