import argparse
import os


class Config:
    def __init__(self, args=None):
        if args is None:
            args = parse_args()

        self.confluence_url = (
            args.confluence_url or
            os.environ.get('CONFLUENCE_URL')
        )
        self.confluence_username = (
            args.confluence_username or
            os.environ.get('CONFLUENCE_USERNAME')
        )
        self.confluence_password = (
            args.confluence_password or
            os.environ.get('CONFLUENCE_PASSWORD')
        )
        self.confluence_space_id = (
            args.confluence_space_id or
            os.environ.get('CONFLUENCE_SPACE_ID')
        )
        self.confluence_parent_page_id = (
            args.confluence_parent_page_id or
            os.environ.get('CONFLUENCE_PARENT_PAGE_ID')
        )
        self.markdown_folder = (
            args.markdown_folder or
            os.environ.get('MARKDOWN_FOLDER') or
            './'
        )
        self.confluence_ignorefile = (
            args.confluence_ignorefile or
            os.environ.get('CONFLUENCE_IGNOREFILE')
        )
        self.confluence_search_pattern = (
            args.confluence_search_pattern or
            os.environ.get('CONFLUENCE_SEARCH_PATTERN') or
            '(autogenerated)'
        )
        self.validate()

    def validate(self):
        missing_fields = []

        if not self.confluence_url:
            missing_fields.append("confluence_url")
        if not self.confluence_username:
            missing_fields.append("confluence_username")
        if not self.confluence_password:
            missing_fields.append("confluence_password")
        if not self.confluence_space_id:
            missing_fields.append("confluence_space_id")
        if not self.confluence_parent_page_id:
            missing_fields.append("confluence_parent_page_id")
        if not self.confluence_search_pattern:
            missing_fields.append("confluence_search_pattern")

        if missing_fields:
            raise ValueError("The following configuration fields are "
                             "missing or empty: " + ", ".join(missing_fields))


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Pushes a folder of Markdown files to Confluence, maintaining the "
            "page structure according to the file and folder hierarchy, while "
            "ignoring non-Markdown files."
        )
    )

    parser.add_argument(
        '--confluence-url',
        help="Confluence base URL")
    parser.add_argument(
        '--confluence-username',
        help="Confluence username")
    parser.add_argument(
        '--confluence-password',
        help="Confluence password")
    parser.add_argument(
        '--confluence-space-id',
        help="Confluence space key")
    parser.add_argument(
        '--confluence-parent-page-id',
        help="Parent page ID under which to add the new page")
    parser.add_argument(
        '--markdown-folder',
        help="File or folder containing Markdown files to publish")
    parser.add_argument(
        '--confluence-ignorefile',
        help="Path to a file with patterns to ignore files or directories")
    parser.add_argument(
        '--confluence-search-pattern',
        help="Pattern to search for Markdown files")

    return parser.parse_args()
