name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install coverage
        pip install .

    - name: Run tests
      run: coverage run -m pytest

    - name: Make coverage report
      run: coverage lcov

    - name: Comment coverage report on PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        lcov-file: coverage.lcov
        delete-old-comments: true
